class MaxMethodLines {
    maxMethodLines() {
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
        console.log("Hello, world!");
    }

}