"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestClass = void 0;
/**
 * This is a test class.
 */
class TestClass {
    /**
     * This is a test method.
     */
    testMethod() {
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
    }
}
exports.TestClass = TestClass;
